Fix: Transpiling failing in web.browser.legacy Meteor packages
aldeed/js-message-box pull request #17
Opened 2020-05-16 08:21 UTC by mrauhu

Greetings @aldeed 

I'm updated the `.babelrc` file with config based on the passed object to `setMinimumBrowserVersions()` in Meteor package `socket-stream-client`:

https://github.com/meteor/meteor/blob/release/METEOR%401.10.2/packages/socket-stream-client/server.js

It's pseudo-official Meteor's minimum legacy version for each browser:

```
          "chrome": 16,
          "edge": 12,
          "firefox": 11,
          "ie": 10,
          "safari": 7
```

Fixes: https://github.com/aldeed/js-message-box/issues/16
Fixes: https://github.com/meteor/meteor/issues/11033

Best wishes,
Sergey.

2020-05-17 15:22 UTC, aldeed requested changes
@mrauhu Thank you for trying to solve this. I do not have any desire to support IE 10 since it's dead, but seeing this PR made me realize what the problem is (I think). I added `browserslist` in `package.json`, which is the recommended way to configure `@babel/preset-env`, but I didn't realize this `targets` was overriding that.

Can you try removing `targets` from here entirely and see if that fixes the issue also? That would be my preferred fix.

```json
"presets": [
  "@babel/preset-env"
],
```

2020-05-17 15:24 UTC, aldeed commented
btw you can enter `npx browserslist` in the project dir to see the full list of browsers that should be supported, as long as Babel is actually using the browserslist as its config.

2020-05-18 01:26 UTC, mrauhu commented
@aldeed thanks for suggestion, I'm updated `.babelrc`.

<details>
  <summary>Output of the <code>npx browserlist</code> command has the Internet Explorer 11</summary>
  
  ```
and_chr 80
and_ff 68
and_qq 1.2
and_uc 12.12
android 80
baidu 7.12
chrome 81
chrome 80
chrome 79
edge 80
edge 79
edge 18
firefox 75
firefox 74
firefox 73
firefox 68
ie 11
ios_saf 13.3
ios_saf 13.2
ios_saf 12.2-12.4
kaios 2.5
op_mini all
op_mob 46
opera 67
opera 66
safari 13
safari 12.1
  ```
</details>

2020-05-18 15:53 UTC, aldeed approved these changes

2020-05-18 15:53 UTC, merged

2020-05-18 16:09 UTC, aldeed commented
Released in 0.2.7, and simpl-schema 1.7.2

2020-05-18 16:10 UTC, mrauhu commented
@aldeed thank you.